services:
  # Extend Ichiran's pg service
  pg:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ichiran-network

  # Extend Ichiran's main service  
  main:
    healthcheck:
      test: ["CMD-SHELL", "ichiran-cli --help || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - ichiran-network

  # Add our MCP server
  mcp-server:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      main:
        condition: service_healthy
    environment:
      ICHIRAN_CONTAINER_NAME: main
      ICHIRAN_TIMEOUT: 30000
      NODE_ENV: production
    ports:
      - "8080:8080"
    volumes:
      - mcp_logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - ichiran-network

volumes:
  mcp_logs:

networks:
  ichiran-network:
    driver: bridge