version: '3.8'

# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  mcp-server:
    build:
      target: development
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      NODE_ENV: development
      DEBUG: "mcp:*"
    command: ["npm", "run", "watch"]

  ichiran-main:
    environment:
      DEBUG: "true"
    volumes:
      - ./logs:/app/logs

  ichiran-db:
    ports:
      - "5432:5432"
    volumes:
      - ./logs:/var/log/postgresql