services:
  ichiran-db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: ichiran
      POSTGRES_USER: ichiran
      POSTGRES_PASSWORD: ichiran
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ichiran -d ichiran"]
      interval: 5s
      timeout: 5s
      retries: 5

  ichiran-main:
    build:
      context: .
      dockerfile: Dockerfile.ichiran
      args:
        ICHIRAN_GIT_COMMIT: '11d6e56'
    depends_on:
      ichiran-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://ichiran:ichiran@ichiran-db:5432/ichiran
      ICHIRAN_DB_HOST: ichiran-db
      ICHIRAN_DB_PORT: 5432
      ICHIRAN_DB_NAME: ichiran
      ICHIRAN_DB_USER: ichiran
      ICHIRAN_DB_PASSWORD: ichiran
    healthcheck:
      test: ["CMD-SHELL", "test -f /usr/local/bin/ichiran-cli && echo 'CLI ready' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ichiran_cache:/app/cache

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    depends_on:
      ichiran-main:
        condition: service_healthy
    environment:
      MCP_SERVER_PORT: 8080
      MCP_TRANSPORT: stdio
      ICHIRAN_CONTAINER_NAME: ichiran-main
      ICHIRAN_TIMEOUT: 30000
      ICHIRAN_MAX_CONCURRENT: 10
      CACHE_TTL: 3600
      MAX_TEXT_LENGTH: 10000
      MAX_BATCH_SIZE: 50
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  ichiran_cache:

networks:
  default:
    driver: bridge